pipeline {
   	agent any
   	environment {
        CHECKED_IN = "";
    }

    parameters {
        string( name: 'UB_PROJECT_NAME', 
            defaultValue: 'cora-testrelease', 
            description: 'Name of the project to build')
        string( name: 'UB_BRANCH_NAME', 
            defaultValue: 'master', 
            description: 'Name of the branch to build')
        string( name: 'FORCE_RELEASE', 
            defaultValue: "0", 
            description: 'Wheter the project has to be build even no dependencies chages have been found. Force release = 1, otherwise 0')
    }
    tools {
        jdk 'Cora OpenJDK'
        maven 'Maven 3.6.x'
    }
    stages {
        stage("checkout"){
            steps{
            	echo "Project: ${UB_PROJECT_NAME}"
            	echo "FORCE_RELEASE: ${FORCE_RELEASE}"
                withCredentials([string(credentialsId: '124b7411-d19a-4d4c-baa4-0769d04ff0be', variable: 'TOKEN'),string(credentialsId: '2a106c39-922c-4d77-9828-916e98b8a95a', variable: 'USERNAME')]) {
                    sh 'git clone https://$TOKEN@github.com/lsu-ub-uu/$UB_PROJECT_NAME.git $UB_PROJECT_NAME -b $UB_BRANCH_NAME'
                }
            }
        }
        stage("update dependencies"){
            steps {
            	sh 'mvn -f $UB_PROJECT_NAME versions:update-parent versions:update-properties -DgenerateBackupPoms=false -Dmaven.version.rules="https://epc.ub.uu.se/jenkins/view/ContinousDelivery/job/cora-jenkins/ws/maven/maven-version-rules.xml"'
            }
        }
        stage("commit updates"){
            steps {
            	dir ("$UB_PROJECT_NAME") {
	                sh 'git config user.email "jenkins@ub"'
	                sh 'git config user.name "Jenkins CI"'
	                script {
	                    CHECKED_IN = sh (script: 'git commit -am="Commit form jenkins"', returnStatus: true, returnStdout: true)
	                }
                }
            }
        }
        stage("build new version"){
            when {
                expression { CHECKED_IN == 0 || FORCE_RELEASE == "1"}
            }
            steps {
            	sh 'mvn -f $UB_PROJECT_NAME -P sonar-cora clean deploy'
            	sh 'mvn -f $UB_PROJECT_NAME -P sonar-cora sonar:sonar'
            }
        }
        stage("push update to git"){
            when {
                expression { CHECKED_IN == 0 }
            }
            steps {
            	dir ("$UB_PROJECT_NAME") {
	                sh 'git push'
	            }
            }
        }
        stage("nothing to update"){
            when {
                expression { CHECKED_IN == 1 && FORCE_RELEASE == "0"}
            }
            steps {
                echo "No dependencies to update, no release created"
            }
        }
        
    }
    post {
        always {
            cleanWs()
        }
    }
}