pipeline {
    agent any
    parameters {
    string( name: 'UB_PROJECT_NAME', 
            defaultValue: 'cora-xx', 
            description: 'version version version')
            
            string( name: 'UB_BRANCH_VERSION', 
            defaultValue: 'x.y', 
            description: 'version version version')
            
            string( name: 'UB_DEV_BRANCH_VERSION', 
            defaultValue: 'x.y', 
            description: 'version version version')
    }
    stages {
        stage('Branch') {
            steps {
                
                build job: 'cora-branch', parameters: [[$class: 'StringParameterValue', name: 'UB_PROJECT_NAME', value: "${params.UB_PROJECT_NAME}" ],
        									[$class: 'StringParameterValue', name: 'UB_BRANCH_VERSION', value: "${params.UB_BRANCH_VERSION}"],
        									[$class: 'StringParameterValue', name: 'UB_DEV_BRANCH_VERSION', value: "${params.UB_DEV_BRANCH_VERSION}"]]
            }
        }
         stage('Release') {
             steps {
               
                build job: 'cora-release', parameters: [[$class: 'StringParameterValue', name: 'UB_PROJECT_NAME', value: "${params.UB_PROJECT_NAME}"],
          [$class: 'StringParameterValue', name: 'UB_BRANCH', value: 'release/'+"${params.UB_BRANCH_VERSION}"]]
             }
         } 
    }
} 