pipeline {
   agent {  label 'minikube' }
   environment {
      NAMESPACE = 'diva-build'
   }
   parameters {
      string(name: 'NAMESPACE', defaultValue: 'diva-build', description: 'Kubernetes namespace to run tests in')
   }
   stages {
       stage('Get Pod Name') {
         steps {
               script {
                  def podName = sh(
                     script: "kubectl -n ${params.NAMESPACE} get pods -l app=diva-playwright -o jsonpath='{.items[0].metadata.name}'",
                     returnStdout: true
                  ).trim()
                  env.POD_NAME = podName
               }
               echo "Playwright pod name: ${env.POD_NAME}"
         }
      }
      stage('Run tests') {
         steps {
               sh """
                  kubectl -n ${params.NAMESPACE} exec ${env.POD_NAME} -- npm run test:ci
               """
         }
      }
   }
   post {
      always {
         sh("""
               rm -rf playwright-report
               rm -f junit-report.xml
               kubectl -n ${params.NAMESPACE} cp ${env.POD_NAME}:playwright-report/ playwright-report
               kubectl -n ${params.NAMESPACE} cp ${env.POD_NAME}:junit-report.xml junit-report.xml
            """)
         junit('junit-report.xml')
         publishHTML([
            reportName: 'Playwright Report',
            reportDir: 'playwright-report',
            reportFiles: 'index.html',
            allowMissing: false,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportTitles: ''
         ])
      }
      success {
         echo 'DiVA Playwright tests passed!'
      }
      failure {
         echo 'DiVA Playwright tests failed!'
      }
   }
}