pipeline {
   agent {  label 'minikube' }
   environment {
      NAMESPACE = 'diva-build'
   }
   parameters {
      string(name: 'NAMESPACE', defaultValue: 'diva-build', description: 'Kubernetes namespace to run tests in')
   }
   stages {
       stage('Get Pod Name') {
         steps {
               script {
                  def podName = sh(
                     script: "kubectl -n ${params.NAMESPACE} get pods -l app=diva-playwright -o jsonpath='{.items[0].metadata.name}'",
                     returnStdout: true
                  ).trim()
                  env.POD_NAME = podName
               }
               echo "Playwright pod name: ${env.POD_NAME}"
         }
      }
      stage('Run tests') {
         steps {
               sh """
                  kubectl -n ${params.NAMESPACE} exec ${env.POD_NAME} -- npm run test:ci
               """
         }
      }
   }
   post {
      always {
         sh("""
               rm -rf playwright-report
               rm -f junit-report.xml
               kubectl -n ${params.NAMESPACE} cp ${env.POD_NAME}:playwright-report/ playwright-report
               kubectl -n ${params.NAMESPACE} cp ${env.POD_NAME}:junit-report.xml junit-report.xml
            """)
         junit('junit-report.xml')
         publishHTML([
            reportName: 'Playwright Report',
            reportDir: 'playwright-report',
            reportFiles: 'index.html',
            allowMissing: false,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportTitles: ''
         ])
      }
      success {
         echo 'DiVA Playwright tests passed!'
         build job: 'helm-package-upload-chart', wait: false, parameters: [
            string(name: 'APPLICATION_NAME', value: 'diva')
         ]
      }
      failure {
         echo 'DiVA Playwright tests failed!'
         mail to: 'leo.danielsson@ub.uu.se,egil.swenning-leyser@ub.uu.se,olov.mckie@ub.uu.se,pere.bartroli@ub.uu.se,marcus.viden@ub.uu.se,sara.tobiasson@ub.uu.se',
              subject: "DiVA Playwright tests FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
              body: "Check Jenkins for details: ${env.BUILD_URL}"
      }
   }
}