pipeline {
    agent any
    environment {
        projectsToUpdate = "";
    }
    stages {
        stage("user input"){
            steps{
                script {
                    projectsToUpdate = input message: 'Enter projects to update dependencies for', 
                    	parameters: [text(defaultValue: 'cora-testrelease1, cora-testrelease2', 
                    	description: 'Project names to try to update dependencies for in master.', 
                    	name: 'PROJECTS_TO_UPDATE', trim: true)]
                    echo "Projects to update: $projectsToUpdate"
                    //echo "Update only dependencies from Cora: $onlyCora"
                }
            }
        }
         stage("loop updates"){
            steps{
                script {
                    echo "updates.."
                    def splittedprojectsToUpdate2 = projectsToUpdate.split(',')
                    splittedprojectsToUpdate2.each() {
                        def trimmed2 = it.trim()
                        def splittedTrimmed2 = trimmed2.split(' ');
                        def project2 = splittedTrimmed2[0].trim();
                        def branch2 = 'master';
                        if(splittedTrimmed2.length > 1){
                            branch2 = splittedTrimmed2[1].trim();
                        }
                        echo "Project:$project2"
                        echo "Branch:$branch2"
                        if(project2 && project2.length() > 0){
	                    	
	                        build job: 'cora-pipeline-update-dependencies', 
	                            parameters: [string(name: 'UB_PROJECT_NAME', value: "$project2"),
	                            	string(name: 'UB_BRANCH_NAME', value: "${branch2}")]
                        }
                    }
                }   
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
} 