pipeline {
   agent any
   environment {
      projectsToUpdate = "";
   }
   parameters {
      text(name: 'PROJECT_NAME',
      defaultValue: '''''',
      description: 'Name of the metadata project to release [cora-metadata, systemone-metadata, diva-metadata, alvin-metadata]')
      
   }
   
   stages {
      stage("Validate project name") {
         steps {
            script {
               def allowedProjects = [
               "cora-metadata",
               "systemone-metadata",
               "diva-metadata",
               "alvin-metadata"
               ]
               if (!allowedProjects.contains(params.PROJECT_NAME)) {
                  error "Invalid PROJECT_NAME: '${params.PROJECT_NAME}'. Allowed values: ${allowedProjects.join(', ')}"
               }
            }
         }
      }
      stage("clone") {
         steps {
            script {
               withCredentials([
               string(credentialsId: '9af4f5c5-4a09-4bbe-9436-2c102765d85b', variable: 'TOKEN'),
               string(credentialsId: '04bc33f5-abdd-4486-b43b-a5900f6fc080', variable: 'USERNAME')
               ]) {
                  sh '''
                  rm -rf "$PROJECT_NAME"
                  git clone https://$USERNAME:$TOKEN@github.com/lsu-ub-uu/$PROJECT_NAME.git "$PROJECT_NAME"
                  '''
               }
            }
         }
      }
      stage("Make sure it is not a release commit") {
         steps {
            script {
               dir("${params.PROJECT_NAME}") {
                  def commitMessage = sh(script: "git log -1 --pretty=%B", returnStdout: true).trim()
                  if (commitMessage.contains("[maven-release-plugin]")) {
                     error("Release commit detected. Aborting.")
                  }
               }
            }
         }
      }
      stage("Release metadata") {
         steps {
            build job: 'cora-pipeline-release-updated-dependencies',
            wait: true,
            parameters: [
            string(name: 'UB_PROJECT_NAME', value: "${params.PROJECT_NAME}"),
            string(name: 'UB_BRANCH_NAME', value: "master"),
            string(name: 'FORCE_RELEASE', value: "1")
            ]
         }
      }
      stage("Call release cora-docker-postgresql") {
         when {
            expression {
               return params.PROJECT_NAME == "cora-metadata"
            }
         }
         steps {
            build job: 'cora-pipeline-release-updated-dependencies-for-dockers-batch',
            wait: true,
            parameters: [
            string(name: 'DOCKERS_TO_RELEASE', value: "cora-docker-postgresql"),
            string(name: 'FORCE_RELEASE', value: "0")
            ]
         }
      }
   }
   post {
      success {
         build job: 'cora-pipeline-release-updated-dependencies-for-dockers-batch',
         wait: false
      }
      always {
         cleanWs()
      }
   }
}