pipeline {
   	agent any
   	environment {
        CHECKED_IN = "";
    }

    parameters {
        string( name: 'UB_PROJECT_NAME', 
            defaultValue: 'cora-testrelease', 
            description: 'Name of the project to build')
        string( name: 'UB_BRANCH_NAME', 
            defaultValue: 'master', 
            description: 'Name of the branch to build')
        string( name: 'UB_DOCKER_PROPERTIES_LIST', 
            defaultValue: 'cora-metadata.version,diva-metadata.version,systemone-metadata.version,alvin-metadata.version,systemone.version,cora-apptokenverifier-war.version,systemonegatekeeperwar.version,diva.version,divacorafitnesse.version,divagatekeeperwar.version,alvin.version,alvingatekeeperwar.version,idplogin.version,alvincorafitnesse.version,alvingatekeeperwar.version,corafitnesse.version', 
            description: 'Name of the branch to build')
    }
    tools {
        jdk 'Cora OpenJDK'
        maven 'Maven 3.6.x'
    }
    stages {
        stage("checkout"){
            steps{
            	echo "Project: ${UB_PROJECT_NAME}"
                withCredentials([string(credentialsId: '124b7411-d19a-4d4c-baa4-0769d04ff0be', variable: 'TOKEN'),string(credentialsId: '2a106c39-922c-4d77-9828-916e98b8a95a', variable: 'USERNAME')]) {
                    sh 'git clone https://$TOKEN@github.com/lsu-ub-uu/$UB_PROJECT_NAME.git $UB_PROJECT_NAME -b $UB_BRANCH_NAME'
                }
            }
        }
        stage("update dependencies"){
            steps {
           	sh 'mvn -f $UB_PROJECT_NAME versions:update-parent versions:update-properties -DgenerateBackupPoms=false -Dmaven.version.rules="https://raw.github.com/lsu-ub-uu/cora-jenkins/master/maven/maven-version-rules.xml"'
            }
        }
        stage("step up dependencies for dockers, latest SNAPSHOT"){
            steps {
            sh 'mvn -f $UB_PROJECT_NAME versions:update-properties -DgenerateBackupPoms=false -DallowSnapshots=true -DincludeProperties=$UB_DOCKER_PROPERTIES_LIST'
            }
        }
        stage("commit updates"){
            steps {
            	dir ("$UB_PROJECT_NAME") {
	                sh 'git config user.email "jenkins@ub"'
	                sh 'git config user.name "Jenkins CI"'
	                script {
	                    CHECKED_IN = sh (script: 'git commit -am="Commit form jenkins"', returnStatus: true, returnStdout: true)
	                }
                }
            }
        }
        stage("build new version"){
            when {
                expression { CHECKED_IN == 0 }
            }
            steps {
            	sh 'mvn -f $UB_PROJECT_NAME -P sonar-cora clean package'
            }
        }
        stage("push update to git"){
            when {
                expression { CHECKED_IN == 0 }
            }
            steps {
            	dir ("$UB_PROJECT_NAME") {
	                sh 'git push'
	            }
            }
        }
        stage("nothing to update"){
            when {
                expression { CHECKED_IN == 1}
            }
            steps {
                echo "No dependencies to update, no release created"
            }
        }
        
    }
    post {
        always {
            cleanWs()
        }
    }
}