pipeline {
   agent {
      label 'minikube'
   }
   parameters {
      string(name: 'TARGET_URL', defaultValue: 'http://172.18.0.15:31682/divaclient' , description: 'DiVA Client test target URL')
      string(name: 'CORA_API_URL', defaultValue: 'http://172.18.0.15:31082/diva/rest', description: 'Cora REST API URL')
      string(name: 'CORA_LOGIN_URL', defaultValue: 'http://172.18.0.15:31182/login/rest', description: 'Cora login REST API URL')
      string(name: 'CORA_USER', defaultValue: 'divaAdmin@cora.epc.ub.uu.se', description: 'Cora token username')
      string(name: 'CORA_APPTOKEN', defaultValue: '49ce00fb-68b5-4089-a5f7-1c225d3cf156', description: 'Cora apptoken')
   }
   stages {
      stage('Ping urls') {
         steps {
            script {
               def urls = [
                  params.TARGET_URL,
                  params.CORA_API_URL,
                  params.CORA_LOGIN_URL
               ]
               for (url in urls) {
                  sh "curl -s -o /dev/null -w '%{http_code}' ${url}"
               }
            }
         }
      }
      stage('Checkout') {
         steps {
            git url: 'https://github.com/lsu-ub-uu/diva-client-e2e', branch: 'master'
         }
      }
      stage('Install dependencies') {
         steps {
            sh 'npm ci'
            sh 'npx playwright install --with-deps'
         }
      }
      stage('Run tests') {
         steps {
            sh 'npm run test:ci'
         }
      }
   }
   post {
      always {
         junit('junit-report.xml')
         publishHTML([
            reportName: 'Playwright Report',
            reportDir: 'playwright-report',
            reportFiles: 'index.html',
            allowMissing: false,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportTitles: ''
         ])
      }
   }
}