pipeline {
   agent {
      docker {
         image 'mcr.microsoft.com/playwright:v1.52.0-noble'
         label 'minikube'
         args '--network=host'
      }
   }
   parameters {
      string(name: 'TARGET_URL', defaultValue: 'http://172.18.0.15:31682/divaclient' , description: 'DiVA Client test target URL')
      string(name: 'CORA_API_URL', defaultValue: 'http://172.18.0.15:31082/diva/rest', description: 'Cora REST API URL')
      string(name: 'CORA_LOGIN_URL', defaultValue: 'http://172.18.0.15:31182/login/rest', description: 'Cora login REST API URL')
      string(name: 'CORA_USER', defaultValue: 'divaAdmin@cora.epc.ub.uu.se', description: 'Cora token username')
      string(name: 'CORA_APPTOKEN', defaultValue: '49ce00fb-68b5-4089-a5f7-1c225d3cf156', description: 'Cora apptoken')
   }
   stages {
      stage('Ping urls') {
         steps {
            script {
               def urls = [
                  params.TARGET_URL,
                  params.CORA_API_URL,
                  params.CORA_LOGIN_URL
               ]
               for (url in urls) {
                  sh "curl -s -o /dev/null -w '%{http_code}' ${url}"
               }
            }
         }
      }
      stage('Checkout') {
         steps {
            git url: 'https://github.com/lsu-ub-uu/diva-client-e2e', branch: 'master', credentialsId: '9af4f5c5-4a09-4bbe-9436-2c102765d85b'
         }
      }
      stage('Run tests') {
         steps {
            sh 'npm ci'
            sh 'npm run test:ci'
         }
      }
   }
   post {
      always {
         junit('junit-report.xml')
         publishHTML([
            reportName: 'Playwright Report',
            reportDir: 'playwright-report',
            reportFiles: 'index.html',
            allowMissing: false,
            alwaysLinkToLastBuild: true,
            keepAll: true,
            reportTitles: ''
         ])
      }
      success {
         echo 'DiVA Client E2E tests passed!'
         build job: 'helm-package-upload-chart', wait: false, parameters: [
            string(name: 'APPLICATION_NAME', value: 'diva')
         ]
      }
      failure {
         echo 'DiVA Client E2E tests failed!'
      }
   }
}