pipeline {
    agent any
    parameters {
    string( name: 'UB_PROJECT_NAME', 
            defaultValue: 'cora-xx', 
            description: 'version version version')
            
            string( name: 'UB_BRANCH_VERSION', 
            defaultValue: 'x.y', 
            description: 'version version version')
            
            string( name: 'UB_DEV_BRANCH_VERSION', 
            defaultValue: 'x.y', 
            description: 'version version version')
    }
    stages {
        stage('Updater') {
            steps {
                build job: 'cora-parent-and-dependencies-updater', 
                parameters: [[$class: 'StringParameterValue', name: 'UB_PROJECT_NAME', value: "${params.UB_PROJECT_NAME}" ],
                [$class: 'StringParameterValue', name: 'params.UB_BRANCH_VERSION', value: "${UB_BRANCH_VERSION}" ],
                [$class: 'StringParameterValue', name: 'params.UB_DEV_BRANCH_VERSION', value: "${UB_DEV_BRANCH_VERSION}" ]]
                }
            post{
                failure {
                    script {
                        error "Error while updating"
                    }
                }
            }
        }
         stage('Branch-Release') {
             steps {
               
                build job: 'cora-branch-release', 
                    parameters: [[$class: 'StringParameterValue', name: 'UB_PROJECT_NAME', value: "${params.UB_PROJECT_NAME}"],
                                [$class: 'StringParameterValue', name: 'UB_BRANCH_VERSION', value: "${params.UB_BRANCH_VERSION}"],
        						[$class: 'StringParameterValue', name: 'UB_DEV_BRANCH_VERSION', value: "${params.UB_DEV_BRANCH_VERSION}"]]
             }
         } 
    }
} 