---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-postgres-volume-claim
  labels:
    app: alvin-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-archive-read-only-volume-claim
  labels:
    app: alvin-archive
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  volumeName: alvin-build-archive-ro-volume

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-archive-read-write-volume-claim
  labels:
    app: alvin-archive
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-converted-files-read-write-volume-claim
  labels:
    app: alvin-converted-files
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-index-read-write-volume-claim
  labels:
    app: alvin-index
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-build-postgres-volume
  labels:
    type: local
    app: alvin-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/minikube/alvin/build/postgresql
  claimRef:
    namespace: alvin-build
    name: alvin-postgres-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-build-archive-ro-volume
  labels:
    type: local
    app: alvin-archive-ro
spec:
  capacity:
    storage: 20Gi
  accessModes: ["ReadOnlyMany"]
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: alvin-archive-ro-volume
    volumeAttributes:
      server: alvin-nfs.alvin-build.svc.cluster.local
      share: /archive-read-only
      mountOptions: "nolock,vers=4,actimeo=60,lookupcache=positive,nocto,noatime,nodiratime"
  claimRef:
    namespace: alvin-build
    name: alvin-archive-read-only-volume-claim
  storageClassName: manual

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-build-archive-rw-volume
  labels:
    type: local
    app: alvin-archive-rw
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/minikube/alvin/build/archive
  claimRef:
    namespace: alvin-build
    name: alvin-archive-read-write-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-build-converted-files-volume
  labels:
    type: local
    app: alvin-converted-files
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/alvin/build/convertedFiles
  claimRef:
    namespace: alvin-build
    name: alvin-converted-files-read-write-volume-claim

---