---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-postgres-volume-claim
  labels:
    app: alvin-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-archive-read-write-volume-claim
  labels:
    app: alvin-archive
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-converted-files-read-write-volume-claim
  labels:
    app: alvin-converted-files
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alvin-previewepc-credentials-read-write-volume-claim
  labels:
    app: alvin-previewepc-credentials-read-write-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-preview-postgres-volume
  labels:
    type: local
    app: alvin-preview-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/alvin/preview/postgresql
  claimRef:
    namespace: alvin-preview
    name: alvin-postgres-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-preview-archive-volume
  labels:
    type: local
    app: alvin-preview-archive
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/alvin/preview/archive
  claimRef:
    namespace: alvin-preview
    name: alvin-archive-read-write-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-preview-converted-files-volume
  labels:
    type: local
    app: alvin-preview-converted-files
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/alvin/preview/convertedFiles
  claimRef:
    namespace: alvin-preview
    name: alvin-converted-files-read-write-volume-claim
    
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: alvin-previewepc-credentials-read-write-volume
  labels:
    type: local
    app: alvin-previewepc-credentials
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/alvin/previewepc/shibboleth
  claimRef:
    namespace: alvin-preview
    name: alvin-previewepc-credentials-read-write-volume-claim
