apiVersion: v1
kind: Secret
metadata:
  name: diva-secret
type: Opaque
data:
  POSTGRES_USER: ZGl2YQ==
  POSTGRES_PASSWORD: ZGl2YQ==
  binaryConverterLoginId: c3lzdGVtb25lQWRtaW5Ac3lzdGVtLmNvcmEudXUuc2U=
  binaryConverterAppToken: NWQzZjNlZDQtNDkzMS00OTI0LTlmYWEtOGVhZjVhYzY0NTdl
  indexLoginId: c3lzdGVtb25lQWRtaW5Ac3lzdGVtLmNvcmEudXUuc2U=
  indexAppToken: NWQzZjNlZDQtNDkzMS00OTI0LTlmYWEtOGVhZjVhYzY0NTdl
  divaClientSessionCookieSecrets: JWVyYlpXN1lBNFUxWDI=
  divaAdminUser: ZGl2YUFkbWluQGNvcmEuZXBjLnViLnV1LnNl
  divaAdminApptoken: NDljZTAwZmItNjhiNS00MDg5LWE1ZjctMWMyMjVkM2NmMTU2
#echo -n 'Hello, World!' | base64
