#postgresql

#pvSharedArchive #ReadWriteMany
#pvcSharedArchiveReadWrite #ReadWriteMany
#pvcSharedArchiveReadOnly #ReadOnlyMany

#pvConvertedFiles #ReadWriteMany
#pvcConvertedFilesReadWrite #ReadWriteMany
#pvcConvertedFilesReadOnly #ReadOnlyMany

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: diva-build-postgres-volume
  labels:
    type: local
    app: diva-build-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/diva/build/postgresql
  claimRef:
    namespace: diva-build
    name: diva-postgres-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: diva-build-archive-volume
  labels:
    type: local
    app: diva-build-archive
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/diva/build/archive
  claimRef:
    namespace: diva-build
    name: diva-archive-read-write-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: diva-build-archive-read-only-volume
  labels:
    type: local
    app: diva-build-archive
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/minikube/diva/build/archive
  claimRef:
    namespace: diva-build
    name: diva-archive-read-only-volume-claim
    
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: diva-build-converted-files-volume
  labels:
    type: local
    app: diva-build-converted-files
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/diva/build/convertedFiles
  claimRef:
    namespace: diva-build
    name: diva-converted-files-read-write-volume-claim
    
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: diva-build-converted-files-read-only-volume
  labels:
    type: local
    app: diva-build-converted-files
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/minikube/diva/build/convertedFiles
  claimRef:
    namespace: diva-build
    name: diva-converted-files-read-only-volume-claim
---
