---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diva-postgres-volume-claim
  labels:
    app: diva-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diva-archive-read-write-volume-claim
  labels:
    app: diva-archive
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diva-converted-files-read-write-volume-claim
  labels:
    app: diva-converted-files
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diva-build-credentials-read-write-volume-claim
  labels:
    app: diva-build-credentials-read-write-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: diva-build-postgres-volume
  labels:
    type: local
    app: diva-build-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/diva/build/postgresql
  claimRef:
    namespace: diva-build
    name: diva-postgres-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: diva-build-archive-volume
  labels:
    type: local
    app: diva-build-archive
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/diva/build/archive
  claimRef:
    namespace: diva-build
    name: diva-archive-read-write-volume-claim

---
	
apiVersion: v1
kind: PersistentVolume
metadata:
  name: diva-build-converted-files-volume
  labels:
    type: local
    app: diva-build-converted-files
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/diva/build/convertedFiles
  claimRef:
    namespace: diva-build
    name: diva-converted-files-read-write-volume-claim
    
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: diva-build-credentials-read-write-volume
  labels:
    type: local
    app: diva-build-credentials
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/diva/build/shibboleth
  claimRef:
    namespace: diva-build
    name: diva-build-credentials-read-write-volume-claim
