---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systemone-postgres-volume-claim
  labels:
    app: systemone-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systemone-archive-read-only-volume-claim
  labels:
    app: systemone-archive
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  volumeName: systemone-archive-ro-volume
      
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systemone-archive-read-write-volume-claim
  labels:
    app: systemone-archive
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systemone-converted-files-read-write-volume-claim
  labels:
    app: systemone-converted-files
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: systemone-index-read-write-volume-claim
  labels:
    app: systemone-index
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: systemone-build-postgres-volume
  labels:
    type: local
    app: systemone-build-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/minikube/systemone/build/postgresql
  claimRef:
    namespace: systemone-build
    name: systemone-postgres-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: systemone-archive-ro-volume
  labels:
    target: systemone
spec:
#Behöver vi ange capacity?
  capacity:
    storage: 20Gi
  accessModes: ["ReadOnlyMany"]
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: systemone-archive-ro-volume
    volumeAttributes:
      server: systemone-nfs.systemone-build.svc.cluster.local
      share: /archive-read-only
      mountOptions: "nolock,vers=4,actimeo=60,lookupcache=positive,nocto,noatime,nodiratime"
  claimRef:
    namespace: systemone-build
    name: systemone-archive-read-only-volume-claim
  storageClassName: manual
  
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: systemone-build-archive-rw-volume
  labels:
    type: local
    app: systemone-build-archive
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/minikube/systemone/build/archive
  claimRef:
    namespace: systemone-build
    name: systemone-archive-read-write-volume-claim

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: systemone-build-converted-files-volume
  labels:
    type: local
    app: systemone-build-converted-files
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/minikube/systemone/build/convertedFiles
  claimRef:
    namespace: systemone-build
    name: systemone-converted-files-read-write-volume-claim
    
---

