pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/playwright:v1.61.0-noble'
            args '--user root'
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        githubProjectProperty(projectUrlStr: 'https://github.com/lsu-ub-uu/diva-client.git/')
        timeout(time: 30, unit: 'MINUTES')
    }

    triggers {
        snapshotDependencies()
        githubPush()
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/lsu-ub-uu/diva-client.git'
            }
        }
        stage('Install') {
            steps {
                sh 'npm ci'
            }
        }
        stage('Checks') {
            parallel {
                stage('Lint') {
                    steps {
                        sh 'npm run lint'
                    }
                }
                stage('Stylelint') {
                    steps {
                        sh 'npm run stylelint'
                    }
                }
                stage('Typecheck') {
                    steps {
                        sh 'npm run typecheck'
                    }
                }
                stage('Unit Tests') {
                    steps {
                        sh 'npm run test:ci'
                    }
                }
            }
        }
        stage('Build') {
            steps {
                build job: 'diva-client'
            }
        }
    }

    post {
        always {
            junit allowEmptyResults: true, testResults: 'junit-report.xml'
            cleanWs()
        }
    }
}
