pipeline {
    agent {
        docker {
            image 'mcr.microsoft.com/playwright:v1.61.0-noble'
            args '--user root'
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        githubProjectProperty(projectUrlStr: 'https://github.com/lsu-ub-uu/diva-client.git/')
        timeout(time: 30, unit: 'MINUTES')
    }

    stages {
        stage('Check if build should trigger') {
            steps {
                script {
                    def ref = env.GITHUB_REF ?: ''

                    if (ref && ref != 'refs/heads/master' && !ref.startsWith('refs/tags/')) {
                        currentBuild.result = 'NOT_BUILT'
                        error("Skipping: webhook ref '${ref}' is not refs/heads/master or a tag")
                    }
                }
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/lsu-ub-uu/diva-client.git'
            }
        }
        stage('Install') {
            steps {
                sh 'npm ci'
            }
        }
        stage('Checks') {
            parallel {
                stage('Lint') {
                    steps {
                        sh 'npm run lint'
                    }
                }
                stage('Stylelint') {
                    steps {
                        sh 'npm run stylelint'
                    }
                }
                stage('Typecheck') {
                    steps {
                        sh 'npm run typecheck'
                    }
                }
                stage('Unit Tests') {
                    steps {
                        sh 'npm run test:ci'
                    }
                }
            }
        }
        stage('Maven build and deploy') {
            steps {
                withMaven(maven: 'Maven latest') {
                    sh 'mvn clean deploy'
                }
            }
        }
        stage('Build docker') {
            steps {
                build job: 'diva-docker-divaclient'
            }
        }
    }

    post {
        always {
            junit allowEmptyResults: true, testResults: 'junit-report.xml'
            cleanWs()
        }
    }
}
