pipeline {
    agent {
        docker {
            image 'node:25.9.0'
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        githubProjectProperty(projectUrlStr: 'https://github.com/lsu-ub-uu/diva-client.git/')
        timeout(time: 30, unit: 'MINUTES')
    }

    stages {
        stage('Check if build should trigger') {
            steps {
                script {
                    def ref = env.GITHUB_REF ?: ''

                    if (ref && ref != 'refs/heads/master' && !ref.startsWith('refs/tags/')) {
                        currentBuild.result = 'NOT_BUILT'
                        error("Skipping: webhook ref '${ref}' is not refs/heads/master or a tag")
                    }
                }
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/lsu-ub-uu/diva-client.git'
            }
        }
        stage('Install') {
            steps {
                sh 'npm ci'
                sh 'npx playwright install --with-deps chromium'
            }
        }
        stage('Checks') {
            parallel {
                stage('Lint') {
                    steps {
                        sh 'npm run lint'
                    }
                }
                stage('Stylelint') {
                    steps {
                        sh 'npm run stylelint'
                    }
                }
                stage('Typecheck') {
                    steps {
                        sh 'npm run typecheck'
                    }
                }
                stage('Unit Tests') {
                    steps {
                        sh 'NO_COLOR=1 npm run test:ci'
                    }
                }
            }
        }
        stage('Build') {
            steps {
                build job: 'diva-client'
            }
        }
        stage('Build docker') {
            steps {
                build job: 'diva-docker-divaclient'
            }
        }
    }

    post {
        always {
            junit allowEmptyResults: true, testResults: 'junit-report.xml'
            archiveArtifacts allowEmptyArchive: true, artifacts: '**/__screenshots__/**/*.png'
            cleanWs()
        }
    }
}
